SIM = icarus  # Use the desired simulator (e.g., questa, xsim, verilator)
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = directCache.sv  # Path to your SV file
TOPLEVEL = directCache  # Name of the top-level module in your SV code
MODULE = test_cache  # Name of the Python test module

include $(shell cocotb-config --makefiles)/Makefile.sim