SIM = icarus  # Use the desired simulator (e.g., questa, xsim, verilator)
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = btb.sv  # Path to your SV file
TOPLEVEL = btb  # Name of the top-level module in your SV code
MODULE = test_btb  # Name of the Python test module

include $(shell cocotb-config --makefiles)/Makefile.sim
